import { GetServerSideProps } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import fetch from "isomorphic-unfetch";

import { BoardGroups, getBoardList } from '../src/client'


export const getServerSideProps: GetServerSideProps = async () => {
  const bgs = await getBoardList()
  return {
    props: {
      boardGroups: bgs,
    },
  }
}

export interface ServerSideProps {
  boardGroups: BoardGroups
}

export default function Home({ boardGroups }: ServerSideProps) {
  return (
    <div>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

    <div>
    {
      boardGroups.map((bg, i) => (
	<div key={i}>
	  <h1>{bg.name}</h1>
	  <ul>
	    {
	      bg.boardList.map((b, j) => 
		<li key={j}>
		  <Link href={{
		    pathname: 'server/[serverId]/board/[boardId]',
		    query: {serverId: b.serverId, boardId: b.boardId}
		  }}
		  >
		    {b.name}
		  </Link>
		</li>
	      )
	    }
	  </ul>
	</div>
      ))
    }
    </div>
    </div>
  )
}
